server:
  port: 2006

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lovebase
    username: root
    password: faolseans8246
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

      security:
        user:
          name: login
          password: parol

    oauth2:
      client:
        registration:
          google:
            client-id: 45812404675-lukrjp81g4cgdkhoiopkato628t1fhti.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  mail:
    host: smtp.gmail.com
    port: 587
    username: feruzbekhamrayev2002@gmail.com
    password: jloh vtda znlg ojtc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    root: DEBUG