server:
  port: ${PORT:2006}

spring:
  datasource:
    url: jdbc:postgresql://cc0gj7hsrh0ht8.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/d8qk4kskekgsiu
    username: u8baa4s0082rud
    password: pb268781a577bbe651841507986d6e9aa31038bd0489efc82bab0c5e6a50b0043
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

      security:
        user:
          name: login
          password: parol

    oauth2:
      client:
        registration:
          google:
            client-id: 45812404675-lukrjp81g4cgdkhoiopkato628t1fhti.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  mail:
    host: smtp.gmail.com
    port: 587
    username: feruzbekhamrayev2002@gmail.com
    password: jloh vtda znlg ojtc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    root: DEBUG